### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by settheworldonfireiii** [vindarel/open-nic#4]
python opennic-set.py
Connecting to http://www.opennicproject.org/nearest-servers/...
Traceback (most recent call last):
  File "opennic-set.py", line 185, in <module>
    exit(main(sys.argv[1:]))
  File "opennic-set.py", line 144, in main
    dns_list = getDnsList()
  File "opennic-set.py", line 71, in getDnsList
    assert nearest[0]
IndexError: list index out of range

**Comment by vindarel** [comment]
Can you try with this one ? https://gitlab.com/vindarel/open-nic/ it received attention last year. (this repo should be a mirror)
